### ISSUE TITLE
Include user/org name in Delete Repository Message

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/dcs#219]
The current delete the repository warning message only includes the repo name and not the organization name.  For forks, this can be confusing and scary to users who may not be entirely sure if they are deleting the fork or the upstream repository.

Would be much more clear if the message included the org/user and the repo name.

**Comment by ethantkoenig** [comment]
This seems like something that could/should be added upstream.

**Comment by ethantkoenig** [comment]
https://github.com/go-gitea/gitea/pull/2886
