### ISSUE TITLE
URL Hyperlinking Does Not Respect Punctuation!

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/dcs#263]
When putting urls in DCS issues, the url hyperlinker does not respect punctuation.

For instance, I added this comment https://git.door43.org/jag3773/Testing/issues/1#issuecomment-12374 and you can see that it hyperlinked the URL *with the period* at the end, which breaks the internet.

This has always been a problem (not a bug recently introduced).

**Comment by richmahn** [comment]
Fixed in Gitea v1.7
