### ISSUE TITLE
Fix bg to have recent database and repos

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/dcs#281]
Fix migration error

**Comment by richmahn** [comment]
Has migration issues from v1.4 to v1.8 (looks like skipping 1.7 is the problem, as 1.4 to 1.7 has no problems). Unless they fix it, this must be done before running `gitea`:

`CREATE INDEX IDX_repository_is_bare ON repository (is_bare);`

`CREATE TABLE `u2f_registration` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `raw` blob,
  `counter` bigint(20) DEFAULT NULL,
  `created_unix` bigint(20) DEFAULT NULL,
  `updated_unix` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_u2f_registration_created_unix` (`created_unix`),
  KEY `IDX_u2f_registration_updated_unix` (`updated_unix`),
  KEY `IDX_u2f_registration_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`
